spring:
  application:
    name: service-registry
  thymeleaf:
    enabled: false     # Disable Thymeleaf 
    
server:
  port: 1111
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false